apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: learning-django
data:
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CSRF_TRUSTED_ORIGINS: ""
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "appuser"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_CONN_MAX_AGE: "60"
